version: '3'
services:
  db:
    image: docker.io/bitnami/mariadb:10.3
    container_name: db-ohrm-app
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${FORWARD_DB_PORT:-3404}:3306"
    volumes:
      - /srv/docker/ohrm/prod/mariadb:/var/lib/mysql
    networks:
      - ohrm 
  orangehrm:
    image: orangehrm/orangehrm:latest
    restart: always
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      - ORANGEHRM_DATABASE_HOST=db
      - ORANGEHRM_DATABASE_USER=${DB_USERNAME}
      - ORANGEHRM_DATABASE_PASSWORD=${DB_PASSWORD}
      - ORANGEHRM_DATABASE_NAME=${DB_DATABASE}
    volumes:
      - /srv/Configs/Orangehrm:/orangehrm
    depends_on:
      - db
    links:
      - db:db
    networks:
      - ohrm
  pma:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: pma-ohrm-app
    restart: always
    ports:
      - '${FORWARD_PMA_PORT:-4404}:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    volumes:
      - './uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini'
    depends_on:
      - db
    networks:
      - ohrm
networks:
  ohrm:
    driver: bridge